### ISSUE TITLE
Subsequent calls only need to clear actions if they were called with the same actions

### ISSUE THREAD

**Issue by ivolimasilva** [moxystudio/redux-mock-store-await-actions#18]
In the README.md, there is the following note:

> **NOTE:** Subsequent calls to `waitForActions` should be preceded by a call to `store.clearActions()`, otherwise the returned `Promise` will resolve immediately.

It should be clearer that `store.clearActions()` is only needed to be called if `waitForActions` are called with the same actions.

**Comment by satazor** [comment]
MR welcome.
