### ISSUE TITLE
Honor the order of array of expected actions

### ISSUE THREAD

**Issue by acostalima** [moxystudio/redux-mock-store-await-actions#6]
Following the example presented in the [README](https://github.com/moxystudio/redux-mock-store-await-actions/blob/master/README.md), the `Promise` will resolve if `LOGIN_START` is dispatched either before or after `LOGIN_SUCCESS` as shown below:
```js
await waitForActions(store, ['LOGIN_START', 'LOGIN_SUCCESS']);

await waitForActions(store, ['LOGIN_SUCCESS', 'LOGIN_START']);
````
**Proposal:** the API shall accept a boolean option to specify whether the order of arrival of dispatched actions should match the order of the array of expected actions. The `Promise` rejects on the first mismatch.

**Comment by satazor** [comment]
+1 for the option.

We need to convert the third argument to an object to allow more options. This will unlock #5
