### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by acostalima** [moxystudio/redux-mock-store-await-actions#7]

**Comment by satazor** [comment]
This is blocked until https://github.com/conventional-changelog/standard-version/issues/213 is resolved.
I had to commit the `package-lock.json` file in https://github.com/moxystudio/yargs-get-help too.

**Comment by satazor** [comment]
Closing this for now since the ecosystem is not prepared. All our packages now have package-lock.json. We might revisit this in the future.
